# Generated by Django 2.2.8 on 2020-06-10 14:26

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=200)),
                ('venue', models.CharField(default='', max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Event Description goes here')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_time', models.TimeField(default=datetime.time(14, 26, 19, 1252))),
                ('sig', models.CharField(choices=[('Catalyst', 'Catalyst'), ('Chronicle', 'Chronicle'), ('Clutch', 'Clutch'), ('Create', 'Create'), ('Credit', 'Credit'), ('Concrete', 'Concrete'), ('Charge', 'Charge'), ('Crypt', 'Crypt'), ('Club', 'Club')], default='', max_length=12)),
                ('no_people_signedup', models.IntegerField(default=0, editable=False)),
                ('members', models.IntegerField(default=3)),
                ('no_people_showedup', models.IntegerField(default=0, editable=False)),
                ('poster_image', models.FileField(upload_to='')),
                ('contact1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to=settings.AUTH_USER_MODEL)),
                ('contact2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('participant1', models.CharField(max_length=50)),
                ('participant2', models.CharField(max_length=50)),
                ('participant3', models.CharField(default='', max_length=50)),
                ('section', models.CharField(default='', max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('phone2', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=200)),
                ('member1', models.CharField(default='', max_length=200)),
                ('member2', models.CharField(blank=True, default='', max_length=200)),
                ('member3', models.CharField(blank=True, default='', max_length=200)),
                ('first_place', models.BooleanField(default=False)),
                ('second_place', models.BooleanField(default=False)),
                ('third_place', models.BooleanField(default=False)),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='', max_length=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
        migrations.CreateModel(
            name='SpectacleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('participant1', models.CharField(max_length=50)),
                ('participant2', models.CharField(max_length=50)),
                ('participant3', models.CharField(default='', max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('phone2', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('roll_no', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
        migrations.CreateModel(
            name='OneMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
        migrations.CreateModel(
            name='FourMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('participant1', models.CharField(max_length=50)),
                ('participant2', models.CharField(max_length=50)),
                ('participant3', models.CharField(max_length=50)),
                ('participant4', models.CharField(default='', max_length=50)),
                ('phone1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('phone2', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number invalid', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDetails')),
            ],
        ),
    ]
