# Generated by Django 2.2.8 on 2020-03-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0083_auto_20200131_1754'),
        ('blogs', '0080_auto_20200128_1926'),
    ]

    operations = [
    ]
