# Generated by Django 2.2.8 on 2020-06-10 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0084_merge_20200331_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 14, 26, 19, 11355)),
        ),
    ]
