# Generated by Django 2.2.8 on 2020-06-10 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0085_auto_20200610_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 16, 3, 33, 868105)),
        ),
    ]
