# Generated by Django 3.0.7 on 2020-12-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('roll_no', models.CharField(default='norollno', max_length=9)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
