# Generated by Django 3.0.7 on 2020-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
