# Generated by Django 3.0.7 on 2020-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200702_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
